### ISSUE TITLE
Create a CI pipeline for ML Service

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/MLService#1]
As a developer, I need to have a CI pipeline which will be run automatically the following development processes:
- Unit Tests
- Code Coverage

**Acceptance Criteria:**
- This pipeline should be run when creating a Pull Request to branch "main'.
- The same pipeline should be run in branch "main" once the Pull Request is approved.
- The pipeline should be using Github-hosted runners.

*Dependency:*
* No dependency

**Comment by GDayne** [comment]
* There is a known failed test in tests 
suggestion: create a task to resolve the unit test failing

**Comment by Rei-Fer** [comment]
- Some tests are failing due to a lack of the binaries that the unit tests were using.

Suggestion: add to the yml to decompress a zip file with the necessary images.

**Comment by GDayne** [comment]
The recommendations were implemented. We use the images for the tests stored in a url and download them in the pipeline, we skipped the failing test and create a task that will solve them. The pipeline is functional.
