### ISSUE TITLE
Generate a XML coverage report

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/MLService#12]
**Descirption:**
The pipeline should generate a coverage report which is needed for the static code analysis.

**Acceptance Criteria:**
- The report should be in XML format and named as coverage.xml

**Dependency:**
No dependencies.

**Comment by Rei-Fer** [comment]
@calebespinoza
**Tasks completed:**
- The pipeline generates a coverage report needed for the static code analysis.
![Image](https://github.com/user-attachments/assets/ef7b6fe5-ddf3-4e5d-8a4c-8c8ba9c2ba75)
