### ISSUE TITLE
Download binaries from the Raw repository in the CI pipeline

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/MLService#6]
**Description:**
Replace the URL from the media files are downloaded and put the new URL from the Raw repository.

**Acceptance Criteria:**
- The download should work with no problemas in the pipeline.

**Dependency:**
This item depends on https://github.com/BC-LT-AT-FS-04/ConfigManage/issues/13

**Comment by GDayne** [comment]
Added in pipeline the Line:

curl -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
        -o file.zip https://nexus.at04.devops.jala.university/repository/at-raw/MLService/MLService.zip

To download the zip file used in tests, however we need to add the Nexus_username and Nexus_password as secrets if not added

**Comment by GDayne** [comment]
We decided to use a TOKEN instead os user and password, for better practices:

- [ ] Create  a TOKEN in Nexus repo for the iamges zip file used in test
- [ ] Add the TOKEN as a secret variable in Github
- [ ] Use the secret in the pipeline

**Comment by GDayne** [comment]
Line in pipeline:

curl -v -u "${{ vars.CONTAINER_REGISTRY_USER }}:${{ secrets.CONTAINER_REGISTRY_PASSWORD }}" -o file.zip http://nexus.at04.devops.jala.university/repository/at-raw/MLService/MLService.zip
